######################################################################
# Automatically generated by qmake (3.0) ? 9? 13 14:15:57 2019
######################################################################

TEMPLATE = app
TARGET = test
INCLUDEPATH += . ../src
QT += widgets

# Input
SOURCES += test.cpp ../src/draggabletabwidget.cpp
HEADERS += ../src/draggabletabwidget.h
